DROP TABLE IF EXISTS `mgfolha_import`.FINANCEIRO;
CREATE TABLE `mgfolha_import`.FINANCEIRO (
    IDSERVIDOR              VARCHAR(8) NOT NULL,
    MES                     VARCHAR(2) NOT NULL,
    ANO                     VARCHAR(4) NOT NULL,
    PARCELA                 VARCHAR(3) NOT NULL,
    IDEVENTO                VARCHAR(3) NOT NULL,
    AUTOMATICA              VARCHAR(1),
    TIPO                    VARCHAR(1),
    REFERENCIA              VARCHAR(10),
    N_VALOR                 NUMERIC(15,2),
    I_PRAZO                 INTEGER,
    I_PRAZOT                INTEGER,
    N_BASEESPECIAL          NUMERIC(15,2),
    N_BASE                  NUMERIC(15,2),
    N_BASEFIXA              NUMERIC(15,2),
    N_DESCONTO              NUMERIC(15,2),
    N_PERCENTUAL            NUMERIC(15,2),
    N_SALDO                 NUMERIC(15,2),
    D_DATA                  DATE,
    I_ANOS                  NUMERIC(15,2),
    I_DEP_IN                INTEGER,
    I_DEP_RP                INTEGER,
    I_DEP_IR                INTEGER,
    I_DIAS                  INTEGER,
    N_VALORPATRONAL         NUMERIC(15,2),
    I_PRIORIDADE            INTEGER,
    I_ANOST                 NUMERIC(15,2),
    N_VALOR_MATERNIDADE     NUMERIC(15,2),
    AD                      CHAR(1),
    ADNUMEROATO             VARCHAR(32),
    ADDATAATO               DATE,
    ADVEICULOPUBLICACAOATO  VARCHAR(255),
    ADDATAINICIO            DATE,
    CGC                     CHAR(1),
    STATUS_ESOCIAL          VARCHAR(255),
    RECIBO_ESOCIAL          VARCHAR(25),
    ID_EVENTO_ESOCIAL       VARCHAR(255)
) ENGINE=INNODB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TABLE IF EXISTS `mgfolha_import`.MENSAL;
CREATE TABLE `mgfolha_import`. MENSAL (
    IDSERVIDOR              VARCHAR(8) NOT NULL,
    MES                     VARCHAR(2) NOT NULL,
    ANO                     VARCHAR(4) NOT NULL,
    PARCELA                 VARCHAR(3) NOT NULL,
    SITUACAO                VARCHAR(20),
    D_SITUACAO              DATE,
    IDCARGO                 VARCHAR(4),
    IDCENTRO                VARCHAR(4),
    IDFUNCAO                VARCHAR(4),
    IDLOCACAO               VARCHAR(4),
    IDPCCS                  VARCHAR(4),
    DESCONTA_IRRF           VARCHAR(1),
    DESCONTA_INSS           VARCHAR(1),
    DESCONTA_RPPS           VARCHAR(1),
    LANCA_ANUENIO           VARCHAR(1),
    LANCA_TRIENIO           VARCHAR(1),
    LANCA_QUINQUENIO        VARCHAR(1),
    LANCA_DECENIO           VARCHAR(1),
    LANCA_SALARIO           VARCHAR(1),
    LANCA_FUNCAO            VARCHAR(1),
    N_BRUTO                 NUMERIC(15,2),
    N_DESCONTOS             NUMERIC(15,2),
    N_LIQUIDO               NUMERIC(15,2),
    N_FALTAS                NUMERIC(15,2),
    PREVIDENCIA             VARCHAR(1),
    DECIMO_ANIV             VARCHAR(1),
    TIPOBENEFICIO           VARCHAR(25),
    SITUACAOFUNCIONAL       VARCHAR(25),
    DESCONTA_SINDICATO      VARCHAR(3),
    GERADO                  VARCHAR(1),
    N_MATERNIDADE           NUMERIC(15,2),
    D_BENEFICIO             DATE,
    RETORNO_OCORRENCIA      VARCHAR(2),
    RETORNO_DATA            DATE,
    RETORNO_VALOR           NUMERIC(15,2),
    RETORNO_DOCUMENTO       VARCHAR(20),
    N_HORAAULA              NUMERIC(15,2),
    CATEGORIA_RECEITA       CHAR(4),
    N_ADNOTURNO             NUMERIC(15,2),
    N_HEXTRA                NUMERIC(15,2),
    HOLERITE_ONLINE         CHAR(1),
    PONTO                   INTEGER DEFAULT 0,
    SIOPE_ATUACAO           VARCHAR(255),
    S1                      CHAR(1),
    S2                      CHAR(1),
    S3                      CHAR(1),
    S4                      CHAR(1),
    S5                      CHAR(1),
    S6                      CHAR(1),
    S7                      CHAR(1),
    O70                     CHAR(1),
    O30                     CHAR(1),
    FG                      CHAR(1),
    FGNUMEROATO             VARCHAR(32),
    FGDATAATO               DATE,
    FGVEICULOPUBLICACAOATO  VARCHAR(255),
    FGDATAINICIO            DATE,
    PLAN_SEGREGACAO         VARCHAR(30),
    TETO_RGPS               VARCHAR(10),
    ABONO_PERM              VARCHAR(10),
    STATUS_ESOCIAL          VARCHAR(255),
    RECIBO_ESOCIAL          VARCHAR(25),
    ID_EVENTO_ESOCIAL       VARCHAR(255)
) ENGINE=INNODB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;